name: Deploy to HF Space
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Git LFS (optional, kalau ada file besar)
        run: git lfs install

      - name: Push to HF Space (force)
        env:
          HF_USERNAME: franzxml
          SPACE: fondasi_matematika_fisika
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          set -e
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"
          # Tambah remote dengan token (jangan echo URL ini ke log)
          git remote add hf "https://${HF_USERNAME}:${HF_TOKEN}@huggingface.co/spaces/${HF_USERNAME}/${SPACE}"
          # Push branch saat ini ke main di Space
          git push hf HEAD:main --force
