name: Deploy to HF Space
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full, include LFS)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        
          lfs: true             

      - name: Setup Git LFS
        run: git lfs install

      - name: Auth HF via netrc
        env:
          HF_USERNAME: franzxml
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          printf "machine huggingface.co\n  login ${HF_USERNAME}\n  password ${HF_TOKEN}\n" > ~/.netrc
          chmod 600 ~/.netrc

      - name: Push to HF Space (force)
        env:
          HF_USERNAME: franzxml
          SPACE: fondasi_matematika_fisika
        run: |
          set -e
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"
          git remote add hf "https://huggingface.co/spaces/${HF_USERNAME}/${SPACE}"
          git push hf HEAD:main --force
